### ISSUE TITLE
python bindings tests not working

### ISSUE THREAD

**Issue by AlyShmahell** [CoppeliaRobotics/bluezero#2]
I'm trying to run the python bindings tests with the b0 version packaged with CoppeliaSim Edu 4.0.0.

b0RemoteApi already works so the problem is not setup-related.

I'm trying to use b0 to facilitate communication between different python scripts which in turn are using b0RemoteApi to communicate with CoppeliaSim.

As a first step I decided to run the example tests provided in this repo, I'm mostly interested in the publish/subscribe model, both the publisher and subscriber seem to be stuck at ```node.init()```.

Any help would be appreciated.

**Comment by fferri** [comment]
Looks like `b0_resolver` is not running or is not reachable.
